### ISSUE TITLE
CMS Content by Record: Change contentDisplayStyle property to use a datasource and follow CMS Collection component conventions.

### ISSUE THREAD

**Issue by ildiavolorosso** [frankcaron/salesforce-cms-component-library#2]
Reference: https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.reference_configuration_tags

The standard CMS Collection component refers to a visual style for the collection layout. Our custom component should follow the convention set by this standard component:
- Change the contentDisplayStyle property to use "Cards" or "Gallery" to "Grid" or "Carousel" and adjust code to respect these values.
- Change the contentDisplayStyle to a dropdown using the datasource attribute available to LWC (see reference above).

**Comment by ildiavolorosso** [comment]
@frankcaron - I'm taking a stab at part of this, but may need your help with GIT.

**Comment by frankcaron** [comment]
Delivered.
