### ISSUE TITLE
CMS Content for This Record: Why is a url required for imageAttribute property?

### ISSUE THREAD

**Issue by ildiavolorosso** [frankcaron/salesforce-cms-component-library#3]
Question on this property:
<property name="imageAttribute" label="CMS Image Field" type="String" description="The developer name for the CMS Content attribute for the image node. Must have a property titled 'url' for the media asset." required="true" default="bannerImage" />

What are we explaining with the text "Must have a property titled 'url' for the media asset."?

**Comment by frankcaron** [comment]
As written right now, the code for displaying the image in the template is deliberately looking for "{item.contentNodes.bannerImage.url}". I haven't made defining the property name with the URL a configurable attribute as I have the bannerImage node, so if we want to make the property containing the URL also configurable, we'll have to refactor that bit at some point.

**Comment by Cheda94** [comment]
Hi, There is some way to open a hyperlink in the same windows that we are using clicking in hyperlink of the image that we are showing in the component?
