### ISSUE TITLE
Display Issue: Advance/Retreat buttons cover up longer CMS Titles

### ISSUE THREAD

**Issue by ildiavolorosso** [frankcaron/salesforce-cms-component-library#4]
When either component is in mode, longer CMS titles end up going under the advance/retreat buttons.
![CMS Issue 1](https://user-images.githubusercontent.com/2405713/98590825-3c710780-2284-11eb-81e4-ccee174f2b02.png)

**Comment by frankcaron** [comment]
@ildiavolorosso How do you want to handle this? Should I ellipsis the text if it's long enough? Move the buttons?

**Comment by ildiavolorosso** [comment]
Hmm. I think we may want to think about moving the arrows. The standard CMS
component positions it on either side of the content, with adjustable
padding. How hard would it be to do that?

**Comment by frankcaron** [comment]
@ildiavolorosso Done! I haven't made the styling adjustable due to it getting real wonky real quick on mobile, but should be good for MVP now.
